insert into product (name, description, image_url)
values ('name #1',
        'description #1',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #2',
        'description #2',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #3',
        'description #3',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #4',
        'description #4',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #5',
        'description #5',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #6',
        'description #6',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #7',
        'description #7',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #8',
        'description #8',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #9',
        'description #9',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #10',
        'description #10',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #11',
        'description #11',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #12',
        'description #12',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #13',
        'description #13',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #14',
        'description #14',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #15',
        'description #15',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #16',
        'description #16',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #17',
        'description #17',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #18',
        'description #18',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #19',
        'description #19',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png'),
       ('name #20',
        'description #20',
        'https://developers.chrome.com/extensions/examples/api/idle/idle_simple/sample-128.png');
